<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>W-Shop | Ecommerce></title>

        <link rel="stylesheet"  type="text/css" href="../css/style.css">

        <link href="/font/css/fontawesome.css" rel="stylesheet">
        <link href="/font/css/brands.css" rel="stylesheet">
        <link href="/font/css/solid.css" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"> 


    
    </head>

    <body>
    
        <header  id="container">
            <h1 class="logo">W-Shop</h1>
            <a href="/">Home<a>
        </header>

    
        <div id="container">

            <?php
                require_once "$caminho";

            ?>


        <div>      
     

     </body>
 </html>