
            <h1 class="display-4 text-primary">Editar Fornecedor</h1>

         
            <form method = 'POST' action="/fornecedores/editarfornecedor" enctype="multipart/form-data"> 
                <input type="hidden" name="id_fornecedor" value="<?=$var['id_fornecedor']?>">
                <div class="form-group">
                    <label for="nome">Nome: </label>
                    <input class="form-control" type="text" required id="nome", name="nome_fornecedor" value="<?=$var['nome_fornecedor']?>">
                </div> 

                <div class="form-group">
                    <label for="site">Site: </label>
                    <input class="form-control" type="url" required id="site", name="site" value="<?=$var['site']?>">
                </div>  

                <div class="form-group">
                        <label for="imagem">Imagem: </imagem>
                        <input class="form-control-file" required type="file" name="logo" id="imagem" > 
                </div>

                <div class="form-group">
                    <textarea class="form-control" required name="descricao"><?=$var['descricao_fornecedor']?></textarea>
                </div>
                <button class="btn btn-primary">Salvar</button>
            </form>
