

    <h1 class="display-4 text-primary">Todos os produtos</h1>
    <h1 class="display-4 text-primary"><?=$var[0]['nome']?></h1>

        <?php
        
            foreach($var as $key=> $var){

        ?>
        <div class="row">
                <div class="card col-md-3 mb-3">

                    <img class="card-img-top" src="<?="/".$var['imagem']?>" width="200" height="250">                   

                    <div class="card-body" id="info">
                        <h2 class="card-title" id="nome"><?=$var['nome']?> </h2>
                        <h2 id="preco" class="card-title">R$<?=$var['preco']?></h2>
                        
                        <div id="descricao" class="card-text">
                            <?=$var['descricao']?> 
                        </div>
                    </div>
                    <div>
                        <a class="btn btn-warning" href="/editar?id=<?=$var['id']?>"><i class="fas fa-edit"></i></a>
                        <a class="btn btn-danger" href="/excluir?id=<?=$var['id']?>"><i class="fas fa-trash-alt"></i></a>
                 </div>
                  

                </div>
               
        </div>
            <?php
            }
            ?>
