

    <h1>Todos os produtos</h1>
    <h1 class="fornecedor"><?=$var[0]['nome']?></h1>

        <?php
        
            foreach($var as $key=> $var){

        ?>
                <div class="produto">

                    <div class="imagem">
                            <img class="img" src="<?="/".$var['imagem']?>" width="200" height="250">
                    </div>

                    <div class="info" id="info">
                        <h2 id="nome"><?=$var['nome']?> </h2>
                        <h2 id="preco" class="preco">R$<?=$var['preco']?></h2>
                        
                        <div id="descricao" class="descricao">
                            <?=$var['descricao']?> 
                        </div>
                    </div>
                    <div>
                        <a href="/editar?id=<?=$var['id']?>"><button><i class="fas fa-edit"></i></button>
                        <a href="/excluir?id=<?=$var['id']?>"> <button class="exluir"><i class="fas fa-trash-alt"></i></button></a>
                    </div>

                </div>
            <?php
            }
            ?>
