           <h1>Todos os fornecedores</h1>
               <?php foreach($var as $key => $value){  ?>
                <div class="row">
                    <div class="col-md-3">
                            <div class="card mb-3">

                                <a href="/fornecedores/todosprodutos?id=<?=$value['id_fornecedor']?>">
                                    <img class="card-img-top" src="<?=$value['logo']?> " width="200" height="250">
                                </a>
                                <div class="card-body">
                                    <h2 class="card-title"><?=$value['nome_fornecedor']?></h2>
                                
                                    <div class="card-text">
                                        <?=$value['descricao_fornecedor']?>
                                    </div>
                                    
                                    <div class="card-text">
                                        Site: <?=$value['site']?>
                                    </div>
                                </div>

                                <div>  
                                    <a class="btn btn-warning" href="/fornecedor/editar?id=<?=$value['id_fornecedor']?>"><i class="fas fa-edit"></i></a>
                                    <a class="btn btn-danger" href="/fornecedor/excluir?id=<?=$value['id_fornecedor']?>"><i class="fas fa-trash-alt"></i></a>
                                </div>

                            </div>
                       
                    </div>
                </div>
                
            <?php }?>