<h1 class="display-4 text-primary">Cadastro de produto</h1>

<form method = 'POST' action="/salvarproduto" enctype="multipart/form-data"> 

    <div class="form-group">
        <label for="nome">Nome: </label>
        <input type="text" required id="nome" name="nome" class="form-control">
    </div>  

    <div class="form-group">
        <label for="preco">Preço: </label>
        <input required type="number" class="form-control" id="preco" name="preco" step='0.01'>
    </div>  

<div class="form-group">
    <label for="fornecedor">Fornecedor</label>
        <select required id="fornecedor" class="form-control" name="fornecedor">

            <option disabled selected name="fornecedor">-- SELECIONE --</option>
            
            <?php
                foreach($var as $key){

            ?>
                <option><?=$key['nome_fornecedor']?></option>
            <?php
            }
            ?>
        </select>
</div>

<div class="form-group">
    <label for="imagem" >Imagem: </imagem>
        <input class="form-control-file" required type="file" name="imagem" id="imagem" > 
</div>


    <textarea class="form-control" required name="descricao" placeholder="Descrição..."></textarea>


<div class="form-group">
    <button class="btn - btn-outline-primary">Cadastrar</button>
</div>

</form>

