
      <h1 class="display-4 text-primary">Editar produto</h1>

     
      <form method = 'POST' action="/editarproduto" enctype="multipart/form-data"> 
      
            <input type="hidden" name="id" value="<?=$var['id']?>">
            <div class="form-group">
                <label for="nome">Nome: </label>
                <input class="form-control" type="text" required id="nome", name="nome" value="<?=$var['nome']?>">
            </div>  

            <div class="form-group">
                <label for="preco">Preço: </label>
                <input class="form-control"required type="number" id="preco", name="preco" step='0.01' value="<?=$var['preco']?>">
            </div>  
            
            <div class="form-group">
                <label for="fornecedor">Fornecedor</label>
                    <select class="form-control" required id="fornecedor" name="fornecedor">
                        <?php
            
                            foreach($var2 as $key => $value){
                                if($value['id_fornecedor'] === $var['id_fornecedor']){
                                    echo "<option selected>".$value['nome_fornecedor']."</option>";
                                }
                                else{
                                    echo "<option>".$value['nome_fornecedor']."</option>";
                                }
                            }
                        ?>
  
                    </select>
            </div>

            <div class="custom-file">
                <label for="imagem">Imagem: </label>
                <input class="custom-file-input" required type="file" name="imagem" id="imagem" > 
                <label class="custom-file-label" for="imagem">Imagem</label>
          
            </div>

          
                <input type="file" class="custom-file-input" id="customFile">
                

            <div class="form-group">
                <textarea class="form-control" required name="descricao"><?=$var['descricao']?></textarea>
            </div>
            <button class="btn btn-outline-primary"><div>Salvar</button></div></button>
    </form>
