          
                <h1>Produto</h1>
                <div class="produto">

                    <div class="imagem">
                            <img class="img" src="<?=$var['imagem']?> " width="200" height="250">
                    </div>

                    <div class="info" id="info">
                        <h2 id="nome"><?=$var['nome']?> (<?=$var['nome_fornecedor']?>) </h2>
                        <h2 id="preco" class="preco">R$<?=$var['preco']?></h2>
                        
                        <div id="descricao" class="descricao">
                            <?=$var['descricao']?> 
                        
                            <div class="atualizacao">
                                <h3>Receba atualizações</h3>
                                <input class="atualizacao" type="email" placeholder="Digite seu melhor e-mail">
                                <button class="atualizacao">Cadastrar</button>
                            </div>
                         
                        </div>
                       
                    </div>
       
                    <div>
                       
                    <a href="/editar?id=<?=$var['id']?>"><button><i class="fas fa-edit"></i></button>

                    <a href="/excluir?id=<?=$var['id']?>"> <button class="exluir"><i class="fas fa-trash-alt"></i></button></a>

                    </div>


                </div>
