
            <div class="lista">
                <a class="link" href="/listarprodutos">Listar produtos</a>
                <a class="link" href="/listarfornecedores">Listar fornecedores</a>
            </div>
            
            <div class="lista">
                <a class="link" href="/cadastrarproduto">Cadastrar produtos</a>
                <a class="link" href="/cadastrarfornecedor">Cadastrar fornecedor</a>
            </div>
