          
               <div class="row d-flex align-self-center">
                    <a class="col-md-5 btn btn-primary ml-4  mb-2" href="/listarprodutos">Listar produtos</a>
                    <a class="col-md-5 btn btn-primary ml-4 mb-2" href="/listarfornecedores">Listar fornecedores</a>
                </div>
                <div class="row">
                    <a class="col-md-5 btn btn-primary  ml-4" href="/cadastrarproduto">Cadastrar produtos</a>
                    <a class="col-md-5 btn btn-primary  ml-4" href="/cadastrarfornecedor">Cadastrar fornecedor</a>
                </div>
        