<h1>Todos os produtos</h1>
        
        <?php foreach($var as $key => $value){
            
         ?>
            <a href="/produto?id=<?=$value['id']?>">
                <div class="produto">

                    <div class="imagem">
                            <img class="img" src="<?=$value['imagem']?> " width="200" height="250">
                      
                    </div>

                    <div class="info">
                        <h2><?=$value['nome']?></h2>
                        
                        <a class="fornecedor" 
                            href="/fornecedores/todosprodutos?id=<?=$value['id_fornecedor']?>&nome=<?=$value['nome_fornecedor']?>">
                            Marca: <?=$value['nome_fornecedor']?>
                        </a>
                    
                        <h2 class="preco">R$<?=$value['preco']?></h2>
                    
                        <div class="descricao">
                            Descrição: <?=$value['descricao']?> 
                        </div>
                    </div>


                </div>
            </a>

        <?php } ?>
